# Generated by Django 4.0.3 on 2023-01-26 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmailJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageSubject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=5000)),
                ('RecurrentDate', models.CharField(max_length=200)),
                ('StartDate', models.CharField(max_length=200)),
                ('EndDate', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Paused', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecurrentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptJobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SenderIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('UserType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='Text_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='SMSJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('RecurrentDate', models.CharField(max_length=200)),
                ('StartDate', models.CharField(max_length=200)),
                ('EndDate', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Paused', models.CharField(max_length=15)),
                ('RecurrentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.recurrenttype')),
                ('SenderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.senderids')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='SMSContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(max_length=100)),
                ('SMS_Job_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.smsjob')),
            ],
        ),
        migrations.CreateModel(
            name='ScriptJob_PHP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Script', models.TextField(max_length=2000)),
                ('RecurrentDate', models.CharField(max_length=200)),
                ('StartDate', models.CharField(max_length=200)),
                ('EndDate', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Paused', models.CharField(max_length=15)),
                ('RecurrentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.recurrenttype')),
                ('Script_Job_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.scriptjobtype')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ScriptJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Script', models.TextField(max_length=2000)),
                ('RecurrentDate', models.CharField(max_length=200)),
                ('StartDate', models.CharField(max_length=200)),
                ('EndDate', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Paused', models.CharField(max_length=15)),
                ('RecurrentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.recurrenttype')),
                ('Script_Job_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.scriptjobtype')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Runtime_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Result_SMS_Runtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResultOutput', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Paused', models.CharField(max_length=15)),
                ('SMS_Job_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.smsjob')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Result_Script_Runtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResultOutput', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Paused', models.CharField(max_length=15)),
                ('Script_Job_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.scriptjob')),
                ('Script_Job_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.scriptjobtype')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Result_Email_Runtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResultOutput', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Paused', models.CharField(max_length=15)),
                ('Email_Job_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.emailjob')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aapf_txn_amt', models.CharField(max_length=200)),
                ('aapf_txn_clientRspRedirectURL', models.CharField(max_length=200)),
                ('aapf_txn_clientTxnWH', models.CharField(max_length=200)),
                ('aapf_txn_cref', models.CharField(max_length=200)),
                ('aapf_txn_currency', models.CharField(max_length=200)),
                ('aapf_txn_datetime', models.CharField(max_length=200)),
                ('aapf_txn_gw_ref', models.CharField(max_length=200)),
                ('aapf_txn_gw_sc', models.CharField(max_length=200)),
                ('aapf_txn_maskedInstr', models.CharField(max_length=200)),
                ('aapf_txn_otherInfo', models.CharField(max_length=200)),
                ('aapf_txn_payLink', models.CharField(max_length=200)),
                ('aapf_txn_payScheme', models.CharField(max_length=200)),
                ('aapf_txn_ref', models.CharField(max_length=200)),
                ('aapf_txn_sc', models.CharField(max_length=200)),
                ('aapf_txn_sc_msg', models.CharField(max_length=200)),
                ('aapf_txn_signature', models.CharField(max_length=200)),
                ('callback', models.CharField(max_length=200)),
                ('Invoice_Type_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.invoicetype')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=3)),
                ('mobile', models.CharField(max_length=15)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.position')),
            ],
        ),
        migrations.AddField(
            model_name='emailjob',
            name='RecurrentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.recurrenttype'),
        ),
        migrations.AddField(
            model_name='emailjob',
            name='SenderEmailAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.emailaddresses'),
        ),
        migrations.AddField(
            model_name='emailjob',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.user'),
        ),
        migrations.CreateModel(
            name='EmailContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(max_length=100)),
                ('Email_Job_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAutoApp.emailjob')),
            ],
        ),
    ]
